management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      userService:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        eventConsumerBufferSize: '10'
        registerHealthIndicator: 'true'
        slidingWindowSize: '10'
        failureRateThreshold: '50'
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: '3'
        minimumNumberOfCalls: '5'
        waitDurationInOpenState: 5s
  retry:
    instances:
      userService:
        maxRetryAttempts: '5'
        waitDuration: 10s
server:
  port: '8082'
spring:
  data:
    mongodb:
      database: users
      uri: mongodb+srv://admin:admin@synechron-spring-boot.4oabrmp.mongodb.net/?retryWrites=true&w=majority
